### PR TITLE
Setup with Python 3.6 suppport --> version 0.3

### PR DESCRIPTION
**Pull request by schlpbch**
@jciskey @Fynardo @adelplanque : Please upload this version, so that we can access this excellent library using pip.

### CODE REVIEW

**Review by Fynardo — APPROVED** [review]

**Comment by schlpbch** [comment]
@Fynardo Diego, can you do a new release?

**Comment by Fynardo** [comment]
I don't have write access on the repo. The best I can do is to approve the changes since I have reviewed them, sorry.

**Comment by hshin-g** [comment]
@jciskey Would you be able to merge this in? Would be great to have an updated version.

**Comment by aurelf** [comment]
It would be nice to push a new version on PiPy, the current version is from May 8, 2017, and does not include the python 3 fixes from PR #2  (which was merged just a bit later in 2017).

Only solution for now is to use [pip from git directly](https://github.com/jciskey/pygraph/issues/3#issue-279109412) 

If this repo is unmaintained, it should be forked and PiPy taken over [PEP-541](https://peps.python.org/pep-0541/), no ?

**Pull request merged**
